## Images
image:
  registry: gcr.io
  repository: google-samples/microservices-demo/frontend
  tag: v0.1.0
  pullPolicy: Always
  port: 8080

global:
  imageRegistry: gcr.io
  name: frontend

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080

lb:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
